### ISSUE TITLE
Allow customization of indent keys

### ISSUE THREAD

**Issue by askvortsov1** [jahudka/mdarea#1]
Hey @jahudka!

Thank you for this library, we use it in flarum's [markdown extension](https://github.com/flarum/markdown), and it's very useful! We're ran into one issue though: the current indent in/indent out shortcuts (ctrl+i, ctrl+o) conflict with our italics shortcut (ctrl+i). There's an issue about it here: https://github.com/flarum/core/issues/2107. We've reached a consensus that it would be preferable to replace those shortcuts with (ctrl+m, ctrl+shift+m) as per https://wikispaces.psu.edu/display/training/The+Word+on+Indenting+Shortcuts to preserve accessibility, but there isn't an option to change these keys in the mdarea config. I put together a gist as a PoC here: https://gist.github.com/askvortsov1/a68b148365c97991b42554c7477489a5. Is this something you might be interested in supporting?

**Comment by jahudka** [comment]
Hi, thanks for the report, I didn't even know there was consensus about universal indentation shortcuts! I'll update mdarea to support configuring your own shortcuts and change the default to be the ones you mention, I think that's best. It'll obviously have to be a new major release since it breaks BC, but there haven't been any other changes to the mdarea code since the last release, so I think it should be okay..

By the way, if I may ask, how did you find out about mdarea? I've developed it mostly for my own projects, I didn't really think anyone else knew about it, so it's a surprise that it's now being used as part of a project as big as Flarum!

**Comment by askvortsov1** [comment]
Thanks for the quick response and for adding this, much appreciated!

Looking at our commit history, it was added in about 2 years ago by a developer who'se since left the team: https://github.com/flarum/markdown/commit/f205ee67473535ed7b153499434e42aac29c9e4f, so unfortunately I don't really know how we found it, but I sure am glad we did!

**Comment by jahudka** [comment]
You're welcome, I'm glad someone is using this, all the more so when it's the Flarum project which I've had on my watchlist for a while now! I've updated the key handling engine to enable custom shortcuts in the last commit referenced above, can you try if it's doing it for you? You can download the minified build directly from the commit. The API has changed - there are no methods to toggle mdarea features anymore, now you can specify everything through the options - I'll have to update the readme in accordance, haven't done that yet. If it works for you I'll release the new major version on Sunday.

**Comment by askvortsov1** [comment]
Looks great, thank you very much! I think I spotted some issues in the demo site configuration though: https://github.com/jahudka/mdarea/commit/1cb6918a06def77bb1408b22fdaf5d82dbc19ba0#r40201606

From testing there's also a few other functionality suggestions that I have, but I'll open them as separate issues as it looks like they were present in previous versions as well :D

**Comment by jahudka** [comment]
Wow, a lot's happened here since Friday! Thanks a lot for all your suggestions, I'll address them separately in their respective issues and / or PRs. The one you mention here I've addressed in a response to the comment you linked. Thank you so much! It's refreshing to have somebody invest their time to try and help out with something I wrote for a change, it doesn't happen often :-)
