### ISSUE TITLE
Support for undo via ctrl+z

### ISSUE THREAD

**Issue by askvortsov1** [jahudka/mdarea#4]
As opposed to regular typing, when you press ctrl+z, changes brought by carats, inlines, tabs, etc aren't reverted. It might be nice to support undoing these changes, although I can imagine this might get a bit complex, and I'm unsure that this is something you necessarily want in a project focused on minimalism.

**Comment by askvortsov1** [comment]
I've done a bit of research on this, and unfortunately it doesn't look like there's an obvious way to do it. Solutions I've found are mostly:

- using document.execCommand, which is deprecated, but the easiest approach. It's also what github's markdown toolbar uses: https://github.com/github/markdown-toolbar-element/blob/master/src/index.ts. (and apparently also what we use for reversions in our markdown toolbar (https://github.com/flarum/markdown/blob/master/js/src/forum/util/insertText.js)
- Manually creating a history stack, which is definitely doable, but not exactly lightweight
- Manually replicating keydown / keyup events, which is also doable, but would result in per-character revision history (a pain to undo), and is overall the worst approach imo.

**Comment by jahudka** [comment]
Yeah, this would also be a welcome and obvious addition. `execCommand` is afaik the way _everyone_ does it, because it's the most well-integrated / native way of doing this. If only Firefox supported `execCommand('insertText')` on `<textarea>`, it wouldn't even be all that complex to implement - I'd just change the `apply` function to use `execCommand` instead of setting the `value` directly. But having to keep around an invisible `contenteditable` and syncing that with the `<textarea>` would probably add a lot of heft to a library that tries to be The Tiniest :-D I'd say if we can just ditch Firefox on this one and support it in other browsers then let's do it. What do you think?

**Comment by askvortsov1** [comment]
Hmm that's a tough one, but I definitely get where you're coming from. Here's an idea: what if mdarea used `execCommand('insertText')` in `apply` by default, but allowed you to pass in a callback to replace `apply` in options? That way, projects that need it could pass in the full https://github.com/github/markdown-toolbar-element/blob/c4a42252d4f2ac84fdadc3784ac8ff18b539d922/src/index.ts#L394 whille keeping mdarea's size small?

**Comment by jahudka** [comment]
Experimenting with `insertText` I've found another issue - selection management. `insertText` replaces the current selection with whichever content you want; but when you _undo_ the `insertText`, the selection is restored to where it was when `insertText` was called; so for example when I want to wrap a selection in quotes, I would replace the selection with quote+selection+quote and then set the selection boundaries so that the quotes appear outside of it; and when I hit undo, the quotes disappear and the selection is where it should be. But in a more complex scenario I might need to shift the selection in order to be able to insert text where I need to - like when indenting a line when the selection doesn't start at the line start - and then restore it after I've replaced the contents; and in those cases an undo will cause the selection to jump to where I shifted it just prior to calling `insertText`. I'm not sure if multiple calls to `insertText` can be composed into a single undo history point, but without that the only way to insert something at multiple places in the textarea at the same time is to replace the whole content between the first insertion point and the last - and undoing that results in the whole content in-between those points to be selected. I'll do some further research on this.. For now, how about I release the fixes and improvements from the other issues and PRs so that you can start prospering from them? :-)

**Comment by askvortsov1** [comment]
Wow, that's a good find, thank you so much for doing that research! Sounds good to me, although there's no rush on Flarum's end: while in beta, we release new versions of our bundled extensions alongside our core releases, and our next release is scheduled for early August :D

**Comment by jahudka** [comment]
Well I'm sure I'd forget to do it in time and then I'd be busy with other stuff and it wouldn't end well :-) so I've released it now. Hope it helps :-) don't hesitate to reach out if you find any other issues. Thanks again for taking the time to report the issues and submitting the PRs!

**Comment by jahudka** [comment]
Back on topic - findings from some further testing:
 - Setting the value of a `<textarea>` by writing to its `value` property will discard undo history for that textarea
 - Calling `document.execCommand('insertText')` multiple times inside a single event handler inserts one history entry per `execCommand` call, which means that while complex operations like indenting / outdenting multiple selected lines of text could be done using multiple `execCommand` calls, the undo history would become cluttered with individual edits - so you'd select 5 lines of text and press `Tab` once to indent them, but then you'd have to press `Ctrl+Z` 5 times to revert that
 - *BUT* it appears that there's a way to do this using a hidden contenteditable `<div>` in combination with calling `execCommand` on both the target textarea _and_ the hidden contenteditable. The issue with using `execCommand` on _just_ the textarea is that to do complex operations using a single `insertText` you need to modify the selection in non-obvious ways - which you can hide when performing the operation by immediately resetting the selection to where it should be, but when undo is then triggered the selection is reset to what it was when `execCommand` was called. In order to take care of this you can store the correct selection start and end in an arbitrary state store and keep track of your position in this store by utilising a hidden contenteditable containing the current state ID; writing to the contenteditable through the `execCommand` method will insert a new undo history entry; you'd then set up a handler for the `input` event on the contenteditable inside of which you'd first `undo` the actual content change in the target textarea using `execCommand` and then you'd restore the selection using the state store.. well, I've tried something like this in a jsFiddle and it seemed to work, anyway :-) so it seems it could be done, the two issues are if and when I'll find the time to implement it and whether or not it would blow up the package size way out of proportion..

**Comment by jahudka** [comment]
One other consideration is that destroying the editor while keeping the textarea itself will also keep the history for the textarea, but destroying the editor should remove the hidden contenteditable, so the history of the selection states would be lost - this might be an issue in AJAX forms and similar scenarios.

**Comment by askvortsov1** [comment]
I've been thinking about this a bit more, and it seems like there's 4 options here:

1. Keep everything exactly as is with no undo functionality
2. Add in very simple undo functionality via insertText, which works, but results in the selection being in the wrong place (perhaps a possible bug-squash could be eliminating selection at all for more complex operations? IE doing the undo, but leaving it with no selected text so that the bug isn't as visible? IMO, the ability to undo far outranks the annoyance of not having a selection after undoing
3. Add in a complex undo system that would bloat the package
4. Go with option 2 (or even option 1), but give the simple function a signature (and pass in neccessary data accordingly) that would allow for the substitution of a more complex replacement (through monkey patching or passing in a callback to options) in libraries that need it 

Out of these, option 4 sounds like the best.

**Comment by jahudka** [comment]
We'll see. I guess implementing full undo support might not be that hard to do in the end, it's just a question of the resulting bundle size - but if we can still fit inside 3kb gzipped I think it might be worth it. I'll look into it when I have the time, probably sometime in the second half of July ;-)

**Comment by askvortsov1** [comment]
Works very well now, thank you very much!
