### ISSUE TITLE
Pressing enter when cursor at beginning of list item doesn't make a new list item

### ISSUE THREAD

**Issue by askvortsov1** [jahudka/mdarea#8]
If in the middle of a list, and you press enter with your cursor directly after the dash, it doesn't move to a new list item. I'm assuming this is in place so that enter can be used to exit out of a list, but if there's content on the same line in front of the cursor, it should insert another list item instead of clearing the current one.

**Comment by jahudka** [comment]
Should be semi-fixed in v1.0.1, try it - I'm saying _semi_-fixed because it's not gonna work properly with numbered lists unless you press enter at the start of the _last_ item in the list - the later items won't get renumbered. But at least it's not exiting the list completely, that is definitely not the correct behaviour, good call on that!

**Comment by askvortsov1** [comment]
Wonderful, thank you so much!!!
